server:
  port: 8085
hm:
  db:
    database: hm-trade
  swagger:
    title: "黑馬商城商品服務接口文件"
    package: com.hmall.trade.controller
spring:
  rabbitmq:
    host: 192.168.111.128 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码