server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.111.128:8848
    gateway:
      default-filters:
      - AddRequestHeader=testHeader, you are so handsome # 全局過濾器，以下所有id都會有此過濾器作用 # for Demo 
      - PrintAny=1,2,3 # for Demo 
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**,/search/**
          filters:
            - AddRequestHeader=testHeader, you are so handsome # 局部過濾器，只有此id有此過濾器作用
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**,/items/**
        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
        - id: trade-service
          uri: lb://trade-service
          predicates:
            - Path=/orders/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/addresses/**,/users/**

hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:  #放行路徑
      - /search/**
      - /users/login
      - /items/**
      - /hi
